project:
  type: website
  output-dir: docs

website:
  title: "name goes here"
  navbar:
    background: primary
    search: true
    right:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
      - href: blog.qmd
        text: blog

  # sidebar:![](thumbnail.jpg)
  #   - title: "Tutorials"
  #     style: "docked"
  #     # background: dark
  #     contents:
  #       - index.qmd
  #       - index.qmd
  #       - about.qmd

format:
  html:
    respect-user-color-scheme: true
    theme:
      dark: [cosmo, theme-dark.scss]
      light: [cosmo, theme-light.scss]
      # cosmo, lumen, journal, minty, morph (fonts), solar, vapor (glowy)
      # 
    css: styles.css
    toc: true



